@echo off
echo Cleaning up broken dependencies...
rmdir /s /q node_modules
del /q package-lock.json
echo Clearing npm cache...
call npm cache clean --force
echo Installing dependencies fresh (this might take a few minutes)...
call npm install
echo Starting Vite server...
call npm run dev
